[build]
  publish = "build"
  command = "npm run netlify-build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10.8.2"
  NODE_OPTIONS = "--max-old-space-size=4096"
  DISABLE_OPENCOLLECTIVE = "true"
  ADBLOCK = "true"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_OPTIONAL = "true"
  NPM_CONFIG_PREFER_OFFLINE = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle OPTIONS preflight requests for PocketBase API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# API proxy for PocketBase
[[redirects]]
  from = "https://vin254.pockethost.io/*"
  to = "https://vin254.pockethost.io/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
